version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - .:/app
    profiles:
      - selenium

  scrape:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - selenium
    profiles: [scrape_movies, scrape_users, scrape_both]

  scrape_movies:
    extends:
      service: scrape
    command: bash -c "sleep 10 && python /app/scripts/scrape_from_movies.py --num_movies 10 --num_reviews_per_movie 1"
    profiles: [scrape_movies]

  scrape_users:
    extends:
      service: scrape
    command: bash -c "sleep 10 && python /app/scripts/scrape_from_users.py --num_users 2 --num_reviews_per_user 1"
    profiles: [scrape_users]

  scrape_both:
    extends:
      service: scrape
    command: >
      bash -c "sleep 10 &&
               python /app/scripts/scrape_from_movies.py --num_movies 10 --num_reviews_per_movie 1 &&
               python /app/scripts/scrape_from_users.py --num_users 10 --num_reviews_per_user 1"
    profiles: [scrape_both]
  
  uploader:
    build:
      context: .
      dockerfile: Dockerfile.uploader
    volumes:
      - .:/app
    command: bash -c "kaggle datasets version -p ./data/ -m 'Hi from docker-compose' "
    profiles: [upload]

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    depends_on:
      - selenium
    volumes:
      - .:/home/jovyan/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    profiles:
      - jupyter
