version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - .:/app
    profiles:
      - selenium
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4444/wd/hub/status | grep '\"ready\":true'"]
      interval: 20s
      timeout: 20s
      retries: 5

  scrape_from_movies:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      selenium:
        condition: service_healthy 
    command: python /app/scripts/scrape_from_movies.py --num_movies 10 --num_reviews_per_movie 1
    profiles: [scrape, scrape_from_movies]
  
  scrape_from_users:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - selenium
    command: python /app/scripts/scrape_from_users.py --num_users 10 --num_reviews_per_user 1
    profiles: [scrape, scrape_from_users]

  uploader:
    build: .
    volumes:
      - .:/app
    #depends_on:
      #- scraper
    command: python scripts/upload_to_kaggle.py
    profiles:
      - upload

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    depends_on:
      - selenium
    volumes:
      - .:/home/jovyan/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    profiles:
      - jupyter
