# Use a slim Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Install only the required packages
COPY requirements-uploader.txt .
RUN pip install --no-cache-dir -r requirements-uploader.txt

# Copy the kaggle.json for API credentials
COPY kaggle.json /root/.kaggle/kaggle.json

# Set permissions on kaggle.json
RUN chmod 600 /root/.kaggle/kaggle.json

# Copy only necessary data files and scripts for uploading
COPY ./data /app/data

