version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
