name: Scrape and Upload Dataset

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Selenium service
        run: docker compose --profile selenium up -d

      - name: Create kaggle.json
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ./kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Run both scraping tasks (if needed)
        run: docker compose --profile selenium --profile scrape_both up --build

      - name: Run dataset upload to Kaggle
        run: docker compose --profile upload up --build
        